### ISSUE TITLE
Expose new APIs to adjust KubeVirt rate limiting

### ISSUE THREAD

**Issue by jcanocan** [kubevirt/hyperconverged-cluster-operator#2152]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:
User expects to run as [many](https://docs.openshift.com/container-platform/4.11/scalability_and_performance/planning-your-environment-according-to-object-maximums.html) VMs in a OpenShift cluster as pods. However, Kubernetes API clients comes a token bucket rate limiter which avoids to congest the kube-apiserver bandwidth. The token bucket rate limiter is configurable through `bust` and `Query Per Second (QPS)` parameters. These parameters [limit the total amount](https://cloud.redhat.com/blog/kubevirt-scale-test-creating-400-vmis-per-node) of VMs that may be scheduled in the cluster. Also, it is required to increase the number of `virt-api` replicas to support the extra requests.

As it is now, users need to apply the following patch to increase the limits:

`$ oc patch hco -n openshift-cnv kubevirt-hyperconverged --type=merge -p '{"metadata":{"annotations":{"kubevirt.kubevirt.io/jsonpatch":"[{\"op\":\"add\",\"path\":\"/spec/configuration\",\"value\":{\"apiConfiguration\":{\"restClient\":{\"rateLimiter\":{\"tokenBucketRateLimiter\":{\"burst\":200,\"qps\":100}}}},\"controllerConfiguration\":{\"restClient\":{\"rateLimiter\":{\"tokenBucketRateLimiter\":{\"burst\":400,\"qps\":200}}}},\"handlerConfiguration\":{\"restClient\":{\"rateLimiter\":{\"tokenBucketRateLimiter\":{\"burst\":400,\"qps\":200}}}},\"webhookConfiguration\":{\"restClient\":{\"rateLimiter\":{\"tokenBucketRateLimiter\":{\"burst\":400,\"qps\":200}}}}}}]"}}}'`

**What you expected to happen**:
I would be more clear and easy for users if the would be an API to set the values, e.g.
``` yaml
Kind: HCO
Spec:
  tuning:
    Static:  # Easy
       burst: 200
       qps: 100
```
or
``` yaml
Kind: HCO
Spec:
  tuning:
    Static:  # Easy
      apiConfiguration:
         burst: 200
         qps: 100
       controllerConfiguration:
         burst: 400
         qps: 200
       handlerConfiguration:
         burst: 400
         qps: 200
       webhookConfiguration:
         burst: 400
         qps: 200
```

I'm not sure which one would be more appropriated. Also, regarding the replica set increasing I'm not sure if it would be good to include it in the same configuration file or just leave it as a separate patch. Another possibility is that this is no longer required because of [this](https://github.com/kubevirt/kubevirt/pull/7401).

Issue tracked in: [CNV-21596](https://issues.redhat.com/browse/CNV-21596)
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`): 4.11.0
- Kubernetes version (use `kubectl version`): 1.24.0
- Cloud provider or hardware configuration: Any
- Install tools:
- Others:
