### ISSUE TITLE
kubevirt metric not visible

### ISSUE THREAD

**Issue by cloudcafetech** [kubevirt/hyperconverged-cluster-operator#3483]
I have setup HCO on RKE2 then install prometheus community stack for monitoring RKE2 k8s cluster.

```
cat << EOF > values.yaml
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
  service:
    type: NodePort
grafana:
  service:
    type: NodePort
alertmanager:
  service:
    type: NodePort
EOF
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install kube-prometheus-stack --create-namespace -n monitoring -f values.yaml prometheus-community/kube-prometheus-stack
```

**kubevirt_vmi** metrics not visible

![Image](https://github.com/user-attachments/assets/9432d33c-bc61-4288-b985-22c5cea527ff)

Please let me know if need to do anything more ?
