### ISSUE TITLE
When the operator and application is tied, use `recreate` strategy

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/hyperconverged-cluster-operator#42]
All the component operators under the HCO should tie together the operator and application so that OLM has full control of the update process (until something more robust is needed).  By default, deployments use the `RollingUpdate` strategy, which will cause new pods to be created while the old one is being deleted.  This can cause confusion in the operator because there's potential for two operators managing the application for a brief period of time.  

Explicitly set strategy to `recreate` to guarantee the old operator is removed before the new one starts. 

@davidvossel's fix on the virt-operator https://github.com/kubevirt/kubevirt/pull/2195
```yaml
spec:
	  replicas: 1
	  selector:
	    matchLabels:
	      kubevirt.io: virt-operator
	  strategy:
	    type: Recreate
```
