### ISSUE TITLE
Pod placement API issue - dry run doesn't occur for all the stanza

### ISSUE THREAD

**Issue by enp0s3** [kubevirt/hyperconverged-cluster-operator#911]
/kind bug

**What happened**:
HCO webhook [code](https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/pkg/apis/hco/v1beta1/hyperconverged_webhook.go#L117-L130) doesn't do dry run for the infra section of the pod placement API. Therefore an incorrect configuration may be provided to the HCO CR.

**What you expected to happen**:
Dry run to fail incorrect configuration of pod placement for infra and workload sections

**How to reproduce it (as minimally and precisely as possible)**:
Provide incorrect configuration to the infra stanza, for example:
```
spec:
    infra:
      nodePlacement:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: role.kubernetes.io/master
                  operator: Equal
                  values:
                  - ""
        tolerations:
        - effect: NoSchedule
          key: master
          operator: Exists
    workloads: {}

```

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`):
```
 » oc get csv -n openshift-cnv
NAME                                      DISPLAY                    VERSION   REPLACES                                  PHASE
kubevirt-hyperconverged-operator.v2.5.0   OpenShift Virtualization   2.5.0     kubevirt-hyperconverged-operator.v2.4.2   Installing

```

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"b66f2d3a6893be729f1b8660309a59c6e0b69196", GitTreeState:"clean", BuildDate:"2020-07-24T07:19:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+d59ce34", GitCommit:"d59ce3486ae3ca3a0c36e5498e56f51594076596", GitTreeState:"clean", BuildDate:"2020-10-08T15:58:07Z", GoVersion:"go1.15.0", Compiler:"gc", Platform:"linux/amd64"}

```
